project:
  type: website
  output-dir: docs

website:
  title: "Ivetta Sergeeva"
  description: "Ivetta Sergeeva: Personal Website"
  search: true
  navbar:
    # change color of navigation top panel, if you want
    #background: "#fcf9f2"
    #foreground: "black"
    #logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd 
      #- teaching.qmd #if you want to use that pages uncomment them but you need to have relevant .qmd
      #- academic_activities.qmd
      - CV.qmd

  #favicon: logo_flavicon.png
  
  page-footer:
    left: |
      <br>
      <br>
      © Ivetta Sergeeva, 2024<br>
      All content licensed under CC BY-NC-SA 4.0<br>
      Opinions are my own and do not represent my employer
    
    right: |
      Made with [R-Studio](https://posit.co/download/rstudio-desktop/) and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [one](https://ucsb-meds.github.io/creating-quarto-websites/) and [two](https://www.andreashandel.com/)

format:
  html:
    theme: [flatly, style.scss]
    css: styles.css
    fontsize: 12pt
    toc: true
    grid:
      sidebar-width: 50px
      body-width: 1200px
    # Additional things to control for all site
    linkcolor: "#384D48"
    #backgroundcolor: "#EBF5EE"
    backgroundcolor: "#E2E2E2"
    #mainfont: "Roboto"
    #fontsize: 12pt 
    

editor: visual

