---
title: "About"
---

I am a social scientist focusing on topics in political behavior, civil society, and emigration. I am currently a PhD researcher in the Department of Political and Social Sciences at the European University Institute (EUI), Florence. In my research, I use a mixed-method methodology with a focus on surveys, statistical modeling, and interviews. Apart from research skills, I have experience working as a project coordinator in civil societies and human rights in the challenging environment of contemporary Russia.

In collaboration with Emil Kamalov, I've co-founded and co-lead two significant projects. The first, OutRush, is a panel survey of Russian political migrants, initiated as both a personal and professional reaction to the 2022 invasion of Ukraine. The second project, Violence Monitor, is a national survey addressing intimate partner violence in Russia. This project uniquely integrates UN methodologies with experimental techniques.

My work has been featured in the [Financial Times](https://www.ft.com/content/5e6bcce9-7bda-4b29-b1b7-f7df6e879fd9), [Deutsche Welle](https://www.dw.com/ru/sdelka-s-sovestu-pokinuvsie-rossiu-i-potom-vernuvsiesa-o-svoem-opyte/a-66896905), [BBC](https://www.bbc.com/russian/features-65686712), [CNBC](https://www.cnbc.com/2022/11/25/georgia-armenia-turkey-economies-boom-with-russian-wealth-migration.html), [Fortune](https://fortune.com/europe/2022/08/20/russia-brain-drain-young-russians-leaving-after-ukraine-war-putin/), The [Moscow Times](https://www.themoscowtimes.com/2023/10/25/15-of-russians-who-fled-war-mobilization-have-returned-survey-a82885).
