---
title: "Publications and Media"
---
<!-- This css code to control size of the page title. Here it is 0 to make it invisible -->

<style>
.title {
  font-size: 0px;
}
</style>



### Peer-reviewed Articles

[Factors of mass support for the government in the times of structural reforms](http://inion.ru/en/publishing/journals-recommended-by-the-high-certification-commission/political-science-old/arkhiv/2021-2-institutcional-nye-reformy/faktory-massovoi-podderzhki-pravitel-stva-v-usloviiakh-provedeniia-strukturnykh-reform-factors-of-mass-support-for-government/). *Political science*, 2021, N 2. Co-authored with B. Sokolov, M. Zavadskaya (in Russian). <details><summary>Abstract</summary>
*Any country in order to stay afloat sooner or later is forced to under-take large-scale internal reforms in various policy areas. However, structural reforms often bear adverse consequences for the population. As the studies of the US and Euro-pean states show, one of the most crucial negative consequences is the decrease in mass support for the government that has initiated the reform. The latter manifests itself in a drop of approval ratings, trust in government, propensity to vote for the incumbent at the forthcoming elections. Such a decrease may lead to decreased legitimacy of the political power, thereby destabilizing the current political system. Is it possible to strike the balance between the necessity of reform and upholding trust on the society’s be-half? Can a government carry out painful reforms without provoking hatred? What conditions facilitate such balance? Although the factors of mass support play the central role in nowadays’ political science, the answers to the questions mentioned above re-main unanswered. This article examines different options available to governments in order to preserve their mass support and legitimacy when conducting unpopular re-forms, with a special emphasis on media framing. Using various theoretical sources and the recent literature on political support in Russia, it identifies various factors that may facilitate the use of the latter option in the Russian context.*
</details>

[National Pride and Subjective Well-being of Russians](https://www.ssoar.info/ssoar/handle/document/74840). *Monitoring of Public Opinion: Economic and Social Changes*. 2020 No. 1. P. 177---205. Co-authored with E. Ponarin (in Russian).
<details><summary>Abstract</summary>
*Since the beginning of the 2000s, subjective well-being of the Russians was growing due to growing incomes and strengthening optimism about the future. However, the worsening economic situation following the crisis in 2008 did not cause the expected fall in subjective well-being rates. One plausible explanation is the growth of national pride. In this paper, it is tested whether or not national pride positively and causally affect happiness and life satisfaction of Russians. Possible compensatory properties of national pride - its hypothetical stronger effect for individuals with low incomes and poor health - are also being investigated. Data: integrated database of the World Values Survey and the European Values Study containing survey data for Russia from 1990 to 2017. Methods: linear regression with instrumental variables. Results: the effect of national pride on subjective well-being is positive and statistically significant (β = 0.26, p-value <0.001), the effect persists while using instrumental variables (β = 0.92, p-value <0.001); the effect is stronger in the period after 2008, as well as for people with low incomes.*
</details>

[Subjective Well-being of Migrants in Russia: Effects of Regional Characteristics and Migration Legislation](https://demreview.hse.ru/index.php/ecsoc/article/view/10407). *Journal of Economic Sociology*. Vol. 21. No 1. Co-authored with E. Ponarin (in Russian).
<details><summary>Abstract</summary>
*Migration is an important and rapidly growing phenomenon in the modern world. Many countries are facing problems with integration and adaption of migrants to new living conditions. Subjective well-being (SWB) can be considered as an indicator of how successfully migrants are adapted and integrated into the host society. Levels of migrants’ SWB are often determined by the same factors as for other people—good health, high salary, employment and youth make them happier. Nonetheless, migrants’ decision to migrate is often led by economic motives, which leads them to overvalue economic characteristics of countries and regions of destination and undervalue non-economic factors. This paper aims to estimate the effects of the economic prosperity (measured by gross regional product) and social capital of Russian regions (measured by general social trust and relative size of the community of the migrant’s compatriots) on the life satisfaction of migrants. In addition, we analyze possible effect of the inclusion of the migrants’ country of origin into Eurasian Customs Union. To answer the proposed questions we employed data of the Russian Longitudinal Monitoring Survey—Higher School of Economics (RLMS-HSE) and statistics provided by Russian Federal State Statistics Service. The main method of analysis is a cross-classified multilevel linear regression modeling. The results show that the economic performance of a region has no effect on the life satisfaction of a migrant. It appears that social factors play a greater role—the effects of general social trust and the relative size of the community of a migrant’s compatriots in a region are positive and statistically significant. We found that inclusion of the country of migrants’ origin into the Eurasian Customs Union positively and significantly affects the life satisfaction of migrants. We associate this effect with a decrease in the economic and psychological costs of migration.*
</details>


### Working Papers

Gendered Response to War: Analysing Patterns of Political Activism of Post-War Russian Emigrants, 2022-2023. Co-authored with K. Nugumanova and I. Sergeeva.
<details><summary>Abstract</summary>
*In the wake of Russia's invasion of Ukraine, gender dynamics in political activism have come to the fore. While the media has reported extensively on the rise of a feminist anti-war resistance movement, the question remains whether there are indeed tangible gender differences in the political behaviour of post-war migrants and, if so, what factors underpin these differences. Although historical narratives depict politics as a predominantly male domain, with women traditionally showing lower levels of political engagement, recent shifts suggest a more complex landscape. Analyzing data from the OutRush panel survey, this study reveals that women, despite reporting heightened feelings of depression and a bleak outlook, consistently exhibit increased political and civic activism compared to men—except in assistance to fellow Russians. Intriguingly, conventional indicators, such as political interest and trust, displayed no gender disparity. A regression analysis posits that feelings of responsibility and the urge for reparations account for the observed gender gap, suggesting that these emotions might play a pivotal role in fueling women's political fervor. To refine our understanding of gendered motivations, a forthcoming Blinder-Oaxaca decomposition analysis will examine whether emotions such as responsibility and reparations drive political and civic engagement differently across genders. The quantitative data is complemented by extensive qualitative research, including interviews with numerous feminist anti-war resistance activists. These interviews explore their personal views on the contrasting experiences of male and female activists, and examines how gender norms and institutional frameworks in their host countries either support or hinder their activist endeavours. This research hopes to illuminate the intricate tapestry of gendered political activism in post-war migration scenarios.*
</details>

Measuring Intimate Partner Violence: Evidence from Field and Survey Experiments. Co-authored with I. Sergeeva.
<details><summary>Abstract</summary>
*Intimate Partner Violence (IPV) is a multifaceted issue that has seen a concerning rise during the global COVID-19 pandemic. While accurate data on IPV prevalence is essential for targeted interventions, traditional administrative data often falls short due to the private nature of IPV and victims' hesitance to seek aid. Sociological surveys, though promising, grapple with challenges like social desirability bias. This study, set against the backdrop of Russia—a country with sparse reliable IPV data—compares various IPV measurement approaches with the face-to-face survey as the benchmark. Our findings reveal that online surveys, devoid of enumerator presence, most effectively capture IPV prevalence rates in Russia. Specifically, these online methods outperformed list experiments and self-administered questionnaires. Notably, women demonstrated a higher IPV disclosure rate in online surveys compared to face-to-face interviews. This research not only underscores the importance of methodological considerations in IPV data collection but also emphasizes the superior efficacy of online surveys in capturing genuine IPV experiences, especially among women.*
</details>

Helping to flee a political crisis: a Conjoint Experiment of Russian Migrants. Co-authored with I. Sergeeva.
<details><summary>Abstract</summary>
*Political crises often provoke mass waves of migration. The most evident examples include the Cuban revolution in 1959, the Islamic revolution in Iran in 1979, the crisis in Venezuela in 2019, and most recently, the crisis in Russia in 2022. These events resulted in mass exoduses, with millions fleeing their homes due to political turmoil. Support from the migrant community can be vital for those trying to escape such dire political situations. Although much research has delved into host countries' perceptions of migrants, the migrants' own views on whom to assist remain less explored. Through the lens of deservingness, this study uses a choice-based conjoint experiment to gauge the attitudes of Russian migrants who left Russia following the onset of its military intervention in Ukraine in 2022. Our findings indicate a preference among these migrants to assist compatriots fleeing due to political reasons, especially if they experience state persecution. We argue this to reflect a sense of political solidarity among emigrants. The context of the political crisis is important: migrants often favor those directly impacted by the crisis and war, including journalists, people of Ukrainian ethnic background, and ethnic minorities heavily conscripted into the conflict. Decisions on assistance are also influenced by factors like age, occupation, gender, and family status.*
</details>

The effect of discrimination on the political behavior of recent migrants: evidence from two waves of the panel survey of new Russian migrants. Co-authored with I. Sergeeva.
<!-- <details><summary>Abstract</summary> -->

<!-- </details> -->

Democracy in Exile? Trajectories of Russian Anti-War Migrants in Eurasia. Co-authored with M. Zavadskaya and I. Sergeeva.
<details><summary>Abstract</summary>
*Can citizens continue to participate in the politics of their home country after migrating to another country? Many examples exist of migrants engaging in their countries of origin's political affairs, such as expatriate voting, forming political communities and hometown associations, donating money to political movements and politicians, advocating for migrants' rights, and other forms of political participation. However, it remains unclear why migrants are willing to continue exercising their ‘voice’ after ‘exit’ and what the main challenges and obstacles are for them to do so while abroad. In this chapter, we analyze the patterns of civic and political engagement among Russian migrants who fled their home country following the invasion of Ukraine in February 2022. Drawing on scholarship in migration studies, we view exit and voice not as mutually exclusive but as mutually reinforcing alternatives. We argue that the way migrants connect with their homeland plays a crucial role in mobilizing and demobilizing them, particularly the connections they have with their employers. The incentives provided by employers may force migrants to dampen their propensity to engage in political activities. To support our argument, we rely on an original survey conducted in March-April and September 2022, as well as semi-structured, in-depth interviews conducted in Georgia, Kazakhstan, Kyrgyzstan, Armenia, and Turkey.*
</details>

Can media framing increase support for health reform? Results of the Conjoint Experiment. Co-authored with B. Sokolov, M. Zavadskaya and I. Sergeeva.
<!-- <details><summary>Abstract</summary> -->

<!-- </details> -->
### Survey Reports

[Six Months in Exile: A New Life of Russian Emigrants](https://osf.io/preprints/socarxiv/epn2c/). *SocArXiv*, 2023. Co-authored with I. Sergeeva, V. Kostenko, M. Zavadskaya.


[Partner violence in Russia: Results of a Series of Surveys](https://violencemonitor.org/report_2023). *Violencemonitor.org*, 2023. Co-authored with I. Sergeeva (in Russian).

[The Great Exodus: A Portrait of New Migrants from Russia. Report on the results of the March 2022 survey](https://outrush.io/report_march_2022). *OutRush project*, 2022. Co-authored with I. Sergeeva, V. Kostenko, M. Zavadskaya.



### Policy and Media Papers

[New Russian Migrants Against the War: Political Action in Russia and Abroad](https://library.fes.de/pdf-files/international/20458.pdf). *Friedrich-Ebert-Stiftung*, 2023. Co-authored with I. Sergeeva, M. Zavadskaya, V. Kostenko. 

[Studying Public Opinion Among Migrants: Challenges and Opportunities](https://www.research-collection.ethz.ch/handle/20.500.11850/599408). *Russian Analytical Digest*, 2023, No. 292. Co-authored with I. Sergeeva, M. Zavadskaya, V. Kostenko. <details><summary>Abstract</summary>
*This issue focuses on the methodological challenges of wartime polling. Denis Volkov engages with criticisms of Levada surveys. Bryn Rosenfeld answers four questions about wartime surveys. Jeremy Morris challenges the very existence of public opinion. Heiko Pleines introduces Discuss Data’s collection of open-access raw opinion data. Anna Biriukova discusses wartime polling by Aleksei Navalny’s Anti-Corruption Foundation. Elena Koneva and Alexander Chilingaryan highlight how the sociology of war is crucial for policymakers. Aleksei Minialo reflects on activist polling. Finally, Emil Kamalov, Ivetta Sergeeva, Margarita Zavadskaya, and Veronica Kostenko discuss their original panel survey data of the most recent wave of emigration.*
</details>

[Abuse, slapping, control: more than 20 million Russians have experienced partner violence](https://www.forbes.ru/forbes-woman/486866-ab-uz-slepki-kontrol-bolee-20-mln-rossian-stalkivalis-s-partnerskim-nasiliem). *Forbes Russia*, 2023. Co-authored with I. Sergeeva.

[The Russian Rhizome: a Social Portrait of New Immigrants](https://re-russia.net/en/expertise/045/). *Re-Russia*, 2023. Co-authored with V. Kostenko, M. Zavadskaya, I. Sergeeva.

[New activists or new 'common folk?' The evolution of political activism among Russian anti-war emigrants](https://russiapost.info/society/common_folk). *Russia.Post*, 2023. Co-authored with M. Zavadskaya, I. Sergeeva, V. Kostenko.

[Russia's 2022 Anti-War Exodus: The Attitudes and Expectations of Russian Migrants](https://www.ponarseurasia.org/russias-2022-anti-war-exodus-the-attitudes-and-expectations-of-russian-migrants/). *Ponars Eurasia*, 2022. Coauthored with V. Kostenko, M. Zavadskaya, I. Sergeeva.

[Happiness in Times of Crisis: How Russians Survive the Covid-19 Pandemic](https://cyberleninka.ru/article/n/schastie-vo-vremya-krizisa-kak-rossiyane-perezhivayut-pandemiyu-covid-19). Sociodigger, 2021. (In Russian).

### Interviews

[Новая русская эмиграция: кто, куда и зачем уезжает из России сегодня](https://open.spotify.com/episode/3n2gfxhNFRaSmrK8BFzE5U). *Юра, мы всё узнали* (Podcast), 2023.

[Эмигранты 2022-го не планируют возвращаться в Россию. Как изменилась их жизнь за полгода? Результаты большого исследования](https://paperpaper.ru/emigranty-2022-go-ne-planiruyut-vozvrashat/). *Бумага*, 2023.

[Det største brain drain i 30 år: Ressourcestærke russere som Antonina har startet et nyt liv i udlandet](https://www.information.dk/udland/2023/02/stoerste-brain-drain-30-aar-ressourcestaerke-russere-antonina-startet-nyt-liv-udlandet). *Information* (Denmark), 2023.

[Более 20 миллионов россиян сталкивались с партнерским насилием](https://www.mosfm.com/audios/151399). *Москва FM*, 2023.

[Young scholars in our professional team: interview for university page](https://spb.hse.ru/en/ma/econasia/news/382861781.html). *Higher School of Economics*, 2020.



